config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
dotfiles:
  d_lazygit:
    src: config/lazygit
    dst: ~/.config/lazygit
  d_nvim:
    src: config/nvim
    dst: ~/.config/nvim
  f_tmux.conf.local:
    src: tmux.conf.local
    dst: ~/.tmux.conf.local
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
  d_ghostty:
    src: config/ghostty
    dst: ~/.config/ghostty
  f_config.json:
    src: config/httpie/config.json
    dst: ~/.config/httpie/config.json
  f_config.yml:
    src: config/lazydocker/config.yml
    dst: ~/.config/lazydocker/config.yml
  d_pypoetry:
    src: config/pypoetry
    dst: ~/.config/pypoetry
  f_init.lua:
    src: config/yazi/init.lua
    dst: ~/.config/yazi/init.lua
  f_keymap.toml:
    src: config/yazi/keymap.toml
    dst: ~/.config/yazi/keymap.toml
  f_package.toml:
    src: config/yazi/package.toml
    dst: ~/.config/yazi/package.toml
  f_yazi.toml:
    src: config/yazi/yazi.toml
    dst: ~/.config/yazi/yazi.toml
profiles:
  gmkbot:
    dotfiles:
    - d_lazygit
    - d_nvim
    - f_tmux.conf.local
    - f_zshrc
    - d_ghostty
    - f_config.json
    - f_config.yml
    - d_pypoetry
    - f_init.lua
    - f_keymap.toml
    - f_package.toml
    - f_yazi.toml
