config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
dotfiles:
  d_lazygit:
    src: config/lazygit
    dst: ~/.config/lazygit
  d_nvim:
    src: config/nvim
    dst: ~/.config/nvim
  f_tmux.conf.local:
    src: tmux.conf.local
    dst: ~/.tmux.conf.local
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
  d_ghostty:
    src: config/ghostty
    dst: ~/.config/ghostty
profiles:
  gmkbot:
    dotfiles:
    - d_lazygit
    - d_nvim
    - f_tmux.conf.local
    - f_zshrc
    - d_ghostty
