config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
dotfiles:
  d_lazygit:
    src: config/lazygit
    dst: ~/.config/lazygit
  d_nvim:
    src: config/nvim
    dst: ~/.config/nvim
  f_tmux.conf.local:
    src: tmux.conf.local
    dst: ~/.tmux.conf.local
  d_ghostty:
    src: config/ghostty
    dst: ~/.config/ghostty
  f_config.json:
    src: config/httpie/config.json
    dst: ~/.config/httpie/config.json
  f_config.yml:
    src: config/lazydocker/config.yml
    dst: ~/.config/lazydocker/config.yml
  d_pypoetry:
    src: config/pypoetry
    dst: ~/.config/pypoetry
  f_keymap.toml:
    src: config/yazi/keymap.toml
    dst: ~/.config/yazi/keymap.toml
  f_package.toml:
    src: config/yazi/package.toml
    dst: ~/.config/yazi/package.toml
  f_yazi.toml:
    src: config/yazi/yazi.toml
    dst: ~/.config/yazi/yazi.toml
  f_config.cfg:
    src: config/yandex-disk/config.cfg
    dst: ~/.config/yandex-disk/config.cfg
  d_yd-tools:
    src: config/yd-tools
    dst: ~/.config/yd-tools
  f_zshenv:
    src: zshenv
    dst: ~/.zshenv
  d_zshrc:
    src: config/zshrc
    dst: ~/.config/zshrc
  d_tmux_scripts:
    src: config/scripts/tmux_scripts
    dst: ~/.config/scripts/tmux_scripts
profiles:
  gmkbot:
    dotfiles:
    - d_lazygit
    - d_nvim
    - f_tmux.conf.local
    - d_ghostty
    - f_config.json
    - f_config.yml
    - d_pypoetry
    - f_keymap.toml
    - f_package.toml
    - f_yazi.toml
    - f_config.cfg
    - d_yd-tools
    - f_zshenv
    - d_zshrc
    - d_tmux_scripts
