config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
dotfiles:
  d_lazygit:
    src: config/lazygit
    dst: ~/.config/lazygit
  d_nvim:
    src: config/nvim
    dst: ~/.config/nvim
profiles:
  gmkbot:
    dotfiles:
    - d_lazygit
    - d_nvim
